#include <iostream>
#include <typeinfo>
#include <typeindex>

#include "Typelist.hpp"
#include "loki/Typelist.h"
#include "loki/TypelistMacros.h"

class zwierze {};
class ssak : public zwierze {};
class ptak : public zwierze {};
class maszyna {};
class kon : public ssak {};
class czlowiek : public ssak {};
class pelikan : public ptak {};
class samolot : public ptak, public maszyna {};

using ET1 = TypeList<int>;
using ET1Loki = LOKI_TYPELIST_1(int);
using ET2 = TypeList<int, long int, char>;
using ET2Loki = LOKI_TYPELIST_3(int, long int, char);
using ET3 = TypeList<int, int, int, int, char>;
using ET3Loki = LOKI_TYPELIST_5(int, int, int, int, char);
using ET4 = TypeList<char, float, int, char>;
using ET4Loki = LOKI_TYPELIST_4(char, float, int, char);
using ET5 = TypeList<int, long int, int, bool, int, char, bool>;
using ET5Loki = LOKI_TYPELIST_7(int, long int, int, bool, int, char, bool);
using ET6 = TypeList<samolot, pelikan, ssak, kon, maszyna, czlowiek, zwierze, ptak>;
using ET6Loki = LOKI_TYPELIST_8(samolot, pelikan, ssak, kon, maszyna, czlowiek, zwierze, ptak);

int main() {
	std::cout << "##########################################" << "\n";
	std::cout << "### Usuwanie duplikatow (NoDuplicates) ###" << "\n";
	std::cout << "##########################################" << "\n";
	std::cout << "Testowa lista (ET1): ";
	std::cout << typeid(TypeAt<ET1, 0>::Result).name() << "\n";
	std::cout << "NoDuplicates (size: " << NoDuplicates<ET1>::Result::size << "):\n";
	std::cout << typeid(TypeAt<NoDuplicates<ET1>::Result, 0>::Result).name() << "\n";
	std::cout << "Loki::TL::NoDuplicates (size: " << Loki::TL::Length<Loki::TL::NoDuplicates<ET1Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET1Loki>::Result, 0>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET2): ";
	std::cout << typeid(TypeAt<ET2, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET2, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET2, 2>::Result).name() << "\n";
	std::cout << "NoDuplicates (size: " << NoDuplicates<ET2>::Result::size << "):\n";
	std::cout << typeid(TypeAt<NoDuplicates<ET2>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET2>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET2>::Result, 2>::Result).name() << "\n";
	std::cout << "Loki::TL::NoDuplicates (size: " << Loki::TL::Length<Loki::TL::NoDuplicates<ET2Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET2Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET2Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET2Loki>::Result, 2>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET3): ";
	std::cout << typeid(TypeAt<ET3, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 4>::Result).name() << "\n";
	std::cout << "NoDuplicates (size: " << NoDuplicates<ET3>::Result::size << "):\n";
	std::cout << typeid(TypeAt<NoDuplicates<ET3>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET3>::Result, 1>::Result).name() << "\n";
	std::cout << "Loki::TL::NoDuplicates (size: " << Loki::TL::Length<Loki::TL::NoDuplicates<ET3Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET3Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET3Loki>::Result, 1>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET4): ";
	std::cout << typeid(TypeAt<ET4, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET4, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET4, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET4, 3>::Result).name() << "\n";
	std::cout << "NoDuplicates (size: " << NoDuplicates<ET4>::Result::size << "):\n";
	std::cout << typeid(TypeAt<NoDuplicates<ET4>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET4>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET4>::Result, 2>::Result).name() << "\n";
	std::cout << "Loki::TL::NoDuplicates (size: " << Loki::TL::Length<Loki::TL::NoDuplicates<ET4Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET4Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET4Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET4Loki>::Result, 2>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET5): ";
	std::cout << typeid(TypeAt<ET5, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 4>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 5>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 6>::Result).name() << "\n";
	std::cout << "NoDuplicates (size: " << NoDuplicates<ET5>::Result::size << "):\n";
	std::cout << typeid(TypeAt<NoDuplicates<ET5>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET5>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET5>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<NoDuplicates<ET5>::Result, 3>::Result).name() << "\n";
	std::cout << "Loki::TL::NoDuplicates (size: " << Loki::TL::Length<Loki::TL::NoDuplicates<ET5Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET5Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET5Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET5Loki>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::NoDuplicates<ET5Loki>::Result, 3>::Result).name() << "\n";

	std::cout << "##########################################" << "\n";
	std::cout << "####### Odwracanie listy (Reverse) #######" << "\n";
	std::cout << "##########################################" << "\n";
	std::cout << "Testowa lista (ET1): ";
	std::cout << typeid(TypeAt<ET1, 0>::Result).name() << "\n";
	std::cout << "Reverse (size: " << Reverse<ET1>::Result::size << "):\n";
	std::cout << typeid(TypeAt<Reverse<ET1>::Result, 0>::Result).name() << "\n";
	std::cout << "Loki::TL::Reverse (size: " << Loki::TL::Length<Loki::TL::Reverse<ET1Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET1Loki>::Result, 0>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET2): ";
	std::cout << typeid(TypeAt<ET2, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET2, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET2, 2>::Result).name() << "\n";
	std::cout << "Reverse (size: " << Reverse<ET2>::Result::size << "):\n";
	std::cout << typeid(TypeAt<Reverse<ET2>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET2>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET2>::Result, 2>::Result).name() << "\n";
	std::cout << "Loki::TL::Reverse (size: " << Loki::TL::Length<Loki::TL::Reverse<ET2Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET2Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET2Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET2Loki>::Result, 2>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET3): ";
	std::cout << typeid(TypeAt<ET3, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET3, 4>::Result).name() << "\n";
	std::cout << "Reverse (size: " << Reverse<ET3>::Result::size << "):\n";
	std::cout << typeid(TypeAt<Reverse<ET3>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET3>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET3>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET3>::Result, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET3>::Result, 4>::Result).name() << "\n";
	std::cout << "Loki::TL::Reverse (size: " << Loki::TL::Length<Loki::TL::Reverse<ET3Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET3Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET3Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET3Loki>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET3Loki>::Result, 3>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET3Loki>::Result, 4>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET4): ";
	std::cout << typeid(TypeAt<ET4, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET4, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET4, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET4, 3>::Result).name() << "\n";
	std::cout << "Reverse (size: " << Reverse<ET4>::Result::size << "):\n";
	std::cout << typeid(TypeAt<Reverse<ET4>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET4>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET4>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET4>::Result, 3>::Result).name() << "\n";
	std::cout << "Loki::TL::Reverse (size: " << Loki::TL::Length<Loki::TL::Reverse<ET4Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET4Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET4Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET4Loki>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET4Loki>::Result, 3>::Result).name() << "\n";
	std::cout << "------------------------------------------" << "\n";
	std::cout << "Testowa lista (ET5): ";
	std::cout << typeid(TypeAt<ET5, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 4>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 5>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET5, 6>::Result).name() << "\n";
	std::cout << "Reverse (size: " << Reverse<ET5>::Result::size << "):\n";
	std::cout << typeid(TypeAt<Reverse<ET5>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET5>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET5>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET5>::Result, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET5>::Result, 4>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET5>::Result, 5>::Result).name() << ", ";
	std::cout << typeid(TypeAt<Reverse<ET5>::Result, 6>::Result).name() << "\n";
	std::cout << "Loki::TL::Reverse (size: " << Loki::TL::Length<Loki::TL::Reverse<ET5Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET5Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET5Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET5Loki>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET5Loki>::Result, 3>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET5Loki>::Result, 4>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET5Loki>::Result, 5>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::Reverse<ET5Loki>::Result, 6>::Result).name() << "\n";

	std::cout << "##########################################" << "\n";
	std::cout << "### Najbardziej pochodny (MostDerived) ###" << "\n";
	std::cout << "##########################################" << "\n";
	std::cout << "Testowa lista: ";
	std::cout << typeid(TypeAt<ET6, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 4>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 5>::Result).name() << "\n";
	std::cout << "(schemat dziedziczenia klas dostepny w pliku png)\n";
	std::cout << "MostDerived<ET6, samolot>: " << typeid(MostDerived<ET6, samolot>::Result).name() << "\n";
	std::cout << "Loki::TL::MostDerived<ET6, samolot>: " << typeid(Loki::TL::MostDerived<ET6Loki, samolot>::Result).name() << "\n";
	std::cout << "MostDerived<ET6, czlowiek>: " << typeid(MostDerived<ET6, czlowiek>::Result).name() << "\n";
	std::cout << "Loki::TL::MostDerived<ET6, czlowiek>: " << typeid(Loki::TL::MostDerived<ET6Loki, czlowiek>::Result).name() << "\n";
	std::cout << "MostDerived<ET6, zwierze>: " << typeid(MostDerived<ET6, zwierze>::Result).name() << "\n";
	std::cout << "Loki::TL::MostDerived<ET6, zwierze>: " << typeid(Loki::TL::MostDerived<ET6Loki, zwierze>::Result).name() << "\n";

	std::cout << "##########################################" << "\n";
	std::cout << "############# DerivedToFront #############" << "\n";
	std::cout << "##########################################" << "\n";
	std::cout << "Testowa lista: ";
	std::cout << typeid(TypeAt<ET6, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 4>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 5>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 6>::Result).name() << ", ";
	std::cout << typeid(TypeAt<ET6, 7>::Result).name() << "\n";
	std::cout << "DerivedToFront (size: " << DerivedToFront<ET6>::Result::size << "):\n";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 3>::Result).name() << ", ";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 4>::Result).name() << ", ";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 5>::Result).name() << ", ";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 6>::Result).name() << ", ";
	std::cout << typeid(TypeAt<DerivedToFront<ET6>::Result, 7>::Result).name() << "\n";
	std::cout << "Loki::TL::DerivedToFront (size: " << Loki::TL::Length<Loki::TL::DerivedToFront<ET6Loki>::Result>::value << "):\n";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 0>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 1>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 2>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 3>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 4>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 5>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 6>::Result).name() << ", ";
	std::cout << typeid(Loki::TL::TypeAt<Loki::TL::DerivedToFront<ET6Loki>::Result, 7>::Result).name() << "\n";
	
	return 0;
}
